# Generated by Django 5.2.16 on 2026-07-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, help_text='Common abbreviation, e.g. PM-JAY', max_length=60)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('level', models.CharField(choices=[('central', 'Central Government'), ('state', 'State Government (Maharashtra)')], default='central', max_length=20)),
                ('category', models.CharField(choices=[('insurance', 'Health Insurance & Treatment Cover'), ('maternal', 'Mothers & Newborns'), ('child', 'Children & Adolescents'), ('senior', 'Senior Citizens'), ('disease', 'Specific Disease Programmes'), ('medicine', 'Affordable Medicines & Diagnostics'), ('digital', 'Digital Health Records')], default='insurance', max_length=20)),
                ('headline_benefit', models.CharField(help_text="One line, e.g. 'Rs 5 lakh cashless treatment per family per year'", max_length=200)),
                ('description', models.TextField()),
                ('eligibility', models.TextField(help_text='One condition per line.')),
                ('documents', models.TextField(help_text='One document per line.')),
                ('application_steps', models.TextField(help_text='One step per line, in order.')),
                ('eligible_cards', models.CharField(choices=[('yellow', 'Yellow / Antyodaya card'), ('orange', 'Orange card'), ('white', 'White card'), ('any', 'Any citizen'), ('senior70', 'Age 70 and above')], default='any', help_text='Primary ration card category this scheme is aimed at.', max_length=20)),
                ('where_to_apply', models.CharField(blank=True, max_length=250)),
                ('official_link', models.URLField(blank=True)),
                ('helpline', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=100)),
                ('last_verified', models.DateField(help_text='Date the details were last checked against the official source.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
