# Generated by Django 5.2.16 on 2026-07-24 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hospital_type', models.CharField(choices=[('govt', 'Government'), ('municipal', 'Municipal / Civic'), ('trust', 'Trust / Charitable'), ('private', 'Private')], default='private', max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(db_index=True, max_length=80)),
                ('district', models.CharField(blank=True, max_length=80)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=40)),
                ('emergency_number', models.CharField(blank=True, max_length=40)),
                ('has_emergency', models.BooleanField(default=True, verbose_name='24x7 emergency')),
                ('has_ambulance', models.BooleanField(default=False)),
                ('accepts_pmjay', models.BooleanField(default=False, verbose_name='Empanelled for PM-JAY / MJPJAY')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BedAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('general_available', models.PositiveIntegerField(default=0, verbose_name='General beds free')),
                ('icu_available', models.PositiveIntegerField(default=0, verbose_name='ICU beds free')),
                ('oxygen_available', models.PositiveIntegerField(default=0, verbose_name='Oxygen beds free')),
                ('ventilator_available', models.PositiveIntegerField(default=0, verbose_name='Ventilators free')),
                ('updated_by', models.CharField(blank=True, max_length=80)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_records', to='hospitals.hospital')),
            ],
            options={
                'verbose_name': 'Bed availability record',
                'verbose_name_plural': 'Bed availability records',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='specialisations',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to='hospitals.specialisation'),
        ),
    ]
